# Ruff configuration file
# See: https://docs.astral.sh/ruff/configuration/

# Same as Black.
line-length = 120
indent-width = 4

target-version = "py312"

# https://docs.astral.sh/ruff/rules/
[lint]
select = [
    "E",
    "F",
    "B",
    "I",
    "FAST",
    "A",
    "C4",
    "DTZ",
    "EM",
    "ISC",
    "ICN",
    "LOG",
    "T20",
    "PT",
    "Q",
    "RET",
    "SIM",
    "TID",
    "TC",
    "ARG",
    "PTH",
    "C90",
    "N",
    "PERF",
    "RUF",
]
ignore = ["S101"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
