
name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup uv with caching
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install ruff
        run: uv tool install ruff

      - name: Run ruff check
        run: uv tool run ruff check .

      - name: Run ruff format check
        run: uv tool run ruff format --check .
